<a href="https://colab.research.google.com/github/johnvb21/DeepLearning/blob/main/insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn

In [ ]:
insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

In [ ]:
ct = make_column_transformer(
    (MinMaxScaler(), ['age', 'bmi', 'children']),
    (OneHotEncoder(handle_unknown='ignore'), ['sex', 'smoker', 'region'])
)

In [ ]:
X = insurance.drop('charges', axis=1)
Y = insurance["charges"]
X

age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [ ]:
ct.fit(X_train)

ColumnTransformer(transformers=[('minmaxscaler', MinMaxScaler(),
                                 ['age', 'bmi', 'children']),
                                ('onehotencoder',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['sex', 'smoker', 'region'])])

In [ ]:
X_train_normal = ct.transform(X_train)
X_test_normal = ct.transform(X_test)
X_train_normal

array([[0.60869565, 0.10734463, 0.4       , ..., 1.        , 0.        ,
        0.        ],
       [0.63043478, 0.22491256, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.73913043, 0.23944041, 0.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.86956522, 0.24791499, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.41304348, 0.85122411, 0.4       , ..., 0.        , 0.        ,
        1.        ],
       [0.80434783, 0.37503363, 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
tf.random.set_seed(42)

In [ ]:
model = tf.keras.Sequential([
 tf.keras.layers.Dense(100, input_shape=[11]),
 tf.keras.layers.Dense(10),
 tf.keras.layers.Dense(5), 
 tf.keras.layers.Dense(1)                            
])

In [ ]:
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(lr=0.001),
              metrics=["mae"])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
model.fit(X_train_normal, Y_train, epochs=200)

Epoch 1/200
34/34 [==============================] - 2s 5ms/step - loss: 13344.9980 - mae: 13344.9980
Epoch 2/200
34/34 [==============================] - 0s 7ms/step - loss: 13338.8926 - mae: 13338.8926
Epoch 3/200
34/34 [==============================] - 0s 6ms/step - loss: 13315.4805 - mae: 13315.4805
Epoch 4/200
34/34 [==============================] - 0s 5ms/step - loss: 13242.6367 - mae: 13242.6367
Epoch 5/200
34/34 [==============================] - 0s 6ms/step - loss: 13063.9229 - mae: 13063.9229
Epoch 6/200
34/34 [==============================] - 0s 6ms/step - loss: 12696.6035 - mae: 12696.6035
Epoch 7/200
34/34 [==============================] - 0s 6ms/step - loss: 12035.5264 - mae: 12035.5264
Epoch 8/200
34/34 [==============================] - 0s 6ms/step - loss: 11041.0479 - mae: 11041.0479
Epoch 9/200
34/34 [==============================] - 0s 5ms/step - loss: 9909.0566 - mae: 9909.0566
Epoch 10/200
34/34 [==============================] - 0s 7ms/step - loss: 8878.6738 

In [ ]:
model.evaluate(X_test_normal, Y_test)

9/9 [==============================] - 0s 3ms/step - loss: 3175.2612 - mae: 3175.2612


[3175.26123046875, 3175.26123046875]

In [ ]:
X_test_normal


array([[0.58695652, 0.24791499, 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.39130435, 0.37826204, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.29391983, 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.43478261, 0.32458972, 0.2       , ..., 0.        , 0.        ,
        0.        ],
       [0.7826087 , 0.84611246, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.7173913 , 0.49071832, 0.2       , ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
input=tf.constant([0.2,0.4,0.5,1,0,0,1,1,0,0,1])

In [ ]:
input.shape

TensorShape([11])

In [ ]:
input = tf.expand_dims(input, axis=-2)

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               1200      
                                                                 
 dense_1 (Dense)             (None, 10)                1010      
                                                                 
 dense_2 (Dense)             (None, 5)                 55        
                                                                 
 dense_3 (Dense)             (None, 1)                 6         
                                                                 
Total params: 2,271
Trainable params: 2,271
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.predict(input)

array([[39597.277]], dtype=float32)